namespace Plus.Communication.Packets.Outgoing
{
    public static class ServerPacketHeader
    {
        public const int AchievementProgressedMessageComposer = 2107;
        public const int AchievementScoreMessageComposer = 1968;
        public const int AchievementsMessageComposer = 305;
        public const int AchievementUnlockedMessageComposer = 806;
        public const int ActionMessageComposer = 1631;
        public const int ActivityPointsMessageComposer = 2018;
        public const int AddExperiencePointsMessageComposer = 2156;
        public const int AuthenticationOKMessageComposer = 2491;
        public const int AvailabilityStatusMessageComposer = 2033;
        public const int AvatarAspectUpdateMessageComposer = 2429;
        public const int AvatarEffectActivatedMessageComposer = 1959;
        public const int AvatarEffectAddedMessageComposer = 3315;
        public const int AvatarEffectExpiredMessageComposer = 2228;
        public const int AvatarEffectMessageComposer = 1167;
        public const int AvatarEffectsMessageComposer = 340;
        public const int BadgeDefinitionsMessageComposer = 2501;
        public const int BadgeEditorPartsMessageComposer = 2238;
        public const int BadgesMessageComposer = 717;
        public const int BCBorrowedItemsMessageComposer = 3828;
        public const int BonusRareComposer = 1533;// need struture
        public const int BotInventoryMessageComposer = 3086;
        public const int BroadcastMessageAlertMessageComposer = 3801;
        public const int BuddyListMessageComposer = 3130;
        public const int BuddyRequestsMessageComposer = 280;
        public const int BuildersClubMembershipMessageComposer = 1452;
        public const int CallForHelperErrorMessageComposer = 673;// Ferramenta de Ajudantes
        public const int CallForHelperWindowMessageComposer = 1591;// Ferramenta de Ajudantes
        public const int CallForHelpPendingCallsMessageComposer = 1121;
        public const int CameraPhotoPreviewComposer = 3696; //Camera //ERRO
        public const int CameraPhotoPurchaseOkComposer = 2783; //Camera //ERRO
        public const int CameraPriceComposer = 3878; //Camera //ERRO
        public const int CameraPurchaseOkComposer = 2783;
        public const int CameraStorageUrlMessageComposer = 3696;
        public const int CampaignCalendarDataMessageComposer = 2531;
        public const int CampaignMessageComposer = 1745;
        public const int CanCreateRoomMessageComposer = 378;
        public const int CantConnectMessageComposer = 899;
        public const int CarryObjectMessageComposer = 1474;
        public const int CatalogIndexMessageComposer = 1032;
        public const int CatalogItemDiscountMessageComposer = 2347;
        public const int CatalogOfferMessageComposer = 3388;
        public const int CatalogPageMessageComposer = 804;
        public const int CatalogUpdatedMessageComposer = 1866;
        public const int CfhTopicsInitMessageComposer = 325;
        public const int ChatMessageComposer = 1446;
        public const int CheckGnomeNameMessageComposer = 546;
        public const int CheckPetNameMessageComposer = 1503;
        public const int CloseConnectionMessageComposer = 122;
        public const int CloseHelperSessionMessageComposer = 138;// Ferramenta de Ajudantes
        public const int ClubGiftsMessageComposer = 619;
        public const int CommunityGoalHallOfFameMessageComposer = 2515;
        public const int ConcurrentUsersGoalProgressMessageComposer = 2737;
        public const int CostumNotificationComposer = 909;// test
        public const int CraftableProductsMessageComposer = 1000;// Crafting
        public const int CraftingFoundMessageComposer = 2124;// Crafting
        public const int CraftingRecipeMessageComposer = 2774;// Crafting
        public const int CraftingResultMessageComposer = 3128;// Crafting
        public const int CreditBalanceMessageComposer = 3475;
        public const int DailyQuestComposer = 1878;// need struture
        public const int DanceMessageComposer = 2233;
        public const int DebugConsole = 3284;// need struture
        public const int DoorbellMessageComposer = 2309;
        public const int EffectsListAddComposer = 2867;//EffectsListAdd
        public const int EffectsListEffectEnableComposer = 1959;//EffectsListAdd
        public const int EffectsListRemoveComposer = 2228;//EffectsListAdd
        public const int EndHelperSessionMessageComposer = 1456;// Ferramenta de Ajudantes
        public const int EnforceCategoryUpdateMessageComposer = 3896;
        public const int EpicPopupFrameComposer = 3945;// test
        public const int FavouritesMessageComposer = 151;
        public const int FigureSetIdsMessageComposer = 1450;
        public const int FigureUpdateMessageComposer = 2429;
        public const int FindFriendsProcessResultMessageComposer = 1210;
        public const int FlatAccessDeniedMessageComposer = 878;
        public const int FlatAccessibleMessageComposer = 3783;
        public const int FlatControllerAddedMessageComposer = 2088;
        public const int FlatControllerRemovedMessageComposer = 1327;
        public const int FlatCreatedMessageComposer = 1304;
        public const int FloodControlMessageComposer = 566;
        public const int FloorHeightMapMessageComposer = 1301;
        public const int FloorPlanFloorMapMessageComposer = 3990;
        public const int FloorPlanSendDoorMessageComposer = 1664;
        public const int FollowFriendFailedMessageComposer = 3048;
        public const int ForumsListDataMessageComposer = 3001;// Forum de Grupos
        public const int FreezeLifesComposer = 2324;// freeze
        public const int FriendListUpdateMessageComposer = 2800;
        public const int FriendNotificationMessageComposer = 3082;
        public const int FurniListAddMessageComposer = 104;
        public const int FurniListMessageComposer = 994;
        public const int FurniListNotificationMessageComposer = 2103;
        public const int FurniListRemoveMessageComposer = 159;
        public const int FurniListUpdateMessageComposer = 3151;
        public const int FurniMaticNoRoomError = 3433; //***
        public const int FurniMaticReceiveItem = 468; //***
        public const int FurniMaticRewardsComposer = 3164; //***
        public const int FurnitureAliasesMessageComposer = 1723;
        public const int Game1WeeklyLeaderboardMessageComposer = 2196;
        public const int Game2WeeklyLeaderboardMessageComposer = 2196;
        public const int Game3WeeklyLeaderboardMessageComposer = 2196;
        public const int GameAccountStatusMessageComposer = 2893;
        public const int GameAchievementListMessageComposer = 2265;
        public const int GameListMessageComposer = 222;
        public const int GenericErrorMessageComposer = 1600;
        public const int GetClubComposer = 2405;
        public const int GetGuestRoomResultMessageComposer = 687;
        public const int GetRelationshipsMessageComposer = 2016;
        public const int GetRoomBannedUsersMessageComposer = 1869;
        public const int GetRoomFilterListMessageComposer = 2937;
        public const int GetYouTubePlaylistMessageComposer = 1112;
        public const int GetYouTubeVideoMessageComposer = 1411;
        public const int GiftWrappingConfigurationMessageComposer = 2234;
        public const int GiftWrappingErrorMessageComposer = 1517;
        public const int GnomeBoxMessageComposer = 2380;
        public const int GroupCreationWindowMessageComposer = 2159;
        public const int GroupDeletedMessageComposer = 3129;
        public const int GroupForumDataMessageComposer = 3011;// Forum de Grupos
        public const int GroupForumListingsMessageComposer = 3001;// Forum de Grupos
        public const int GroupForumNewResponseMessageComposer = 2049;// Forum de Grupos
        public const int GroupForumNewThreadMessageComposer = 1862;// Forum de Grupos
        public const int GroupForumReadThreadMessageComposer = 509;// Forum de Grupos
        public const int GroupForumThreadRootMessageComposer = 1073;// Forum de Grupos
        public const int GroupForumThreadUpdateMessageComposer = 2528;// Forum de Grupos
        public const int GroupFurniConfigMessageComposer = 420;
        public const int GroupFurniSettingsMessageComposer = 3293;
        public const int GroupInfoMessageComposer = 1702;
        public const int GroupMembershipRequestedMessageComposer = 1180;
        public const int GroupMembersMessageComposer = 1200;
        public const int GroupMemberUpdatedMessageComposer = 265;
        public const int GuestRoomSearchResultMessageComposer = 52;
        public const int GuideSessionAttachedMessageComposer = 1591;
        public const int GuideSessionDetachedMessageComposer = 138;
        public const int GuideSessionEndedMessageComposer = 1456;
        public const int GuideSessionErrorMessageComposer = 673;
        public const int GuideSessionInvitedToGuideRoomMessageComposer = 219;
        public const int GuideSessionMsgMessageComposer = 841;
        public const int GuideSessionPartnerIsTypingMessageComposer = 1016;
        public const int GuideSessionRequesterRoomMessageComposer = 1847;
        public const int GuideSessionStartedMessageComposer = 3209;
        public const int HabboActivityPointNotificationMessageComposer = 2275;
        public const int HabboClubCenterInfoMessageComposer = 3277;
        public const int HabboClubOffersMessageComposer = 2405;
        public const int HabboGroupBadgesMessageComposer = 2402;
        public const int HabboSearchResultMessageComposer = 973;
        public const int HabboUserBadgesMessageComposer = 1087;
        public const int HandleHelperToolMessageComposer = 1548;// Ferramenta de Ajudantes
        public const int HeightMapMessageComposer = 2753;
        public const int HelperSessionChatIsTypingMessageComposer = 1016;// Ferramenta de Ajudantes
        public const int HelperSessionInvinteRoomMessageComposer = 219;// Ferramenta de Ajudantes
        public const int HelperSessionSendChatMessageComposer = 841;// Ferramenta de Ajudantes
        public const int HelperSessionVisiteRoomMessageComposer = 1847;// Ferramenta de Ajudantes
        public const int HelperToolMessageComposer = 1548;
        public const int HideWiredConfigMessageComposer = 1155;
        public const int HotelClosedAndOpensComposer = 3728;// test
        public const int HotellWillClosedInMinutesComposer = 1050;// test
        public const int IgnoredUsersMessageComposer = 126;
        public const int IgnoreStatusMessageComposer = 207;
        public const int InitCryptoMessageComposer = 1347;
        public const int InitHelperSessionChatMessageComposer = 3209;// Ferramenta de Ajudantes
        public const int InstantMessageErrorMessageComposer = 3359;
        public const int ItemAddMessageComposer = 2187;
        public const int ItemRemoveMessageComposer = 3208;
        public const int ItemsMessageComposer = 1369;
        public const int ItemUpdateMessageComposer = 2009;
        public const int JoinQueueMessageComposer = 2260;
        public const int LatencyResponseMessageComposer = 10;
        public const int LoadGameMessageComposer = 3654;
        public const int LoadJukeboxUserMusicItemsMessageComposer = 2602; // Jukebox
        public const int LoveLockDialogueCloseMessageComposer = 382;
        public const int LoveLockDialogueMessageComposer = 3753;
        public const int LoveLockDialogueSetLockedMessageComposer = 382;
        public const int MaintenanceStatusMessageComposer = 1350;
        public const int ManageGroupMessageComposer = 3965;
        public const int MarketplaceCancelOfferResultMessageComposer = 3264;
        public const int MarketplaceCanMakeOfferResultMessageComposer = 54;
        public const int MarketplaceConfigurationMessageComposer = 1823;
        public const int MarketplaceItemStatsMessageComposer = 725;
        public const int MarketplaceMakeOfferResultMessageComposer = 1359;
        public const int MarketPlaceOffersMessageComposer = 680;
        public const int MarketPlaceOwnOffersMessageComposer = 3884;
        public const int MassEventComposer = -1; //@@@ //error 404
        public const int MatchingPollFinishMessageComposer = 2589;// Quickpolls
        public const int MatchingPollMessageComposer = 2665;// Quickpolls
        public const int MatchingPollResultsMessageComposer = 1066;// Quickpolls
        public const int MessengerErrorMessageComposer = 892;
        public const int MessengerInitMessageComposer = 1605;
        public const int ModeratorInitMessageComposer = 2696;
        public const int ModeratorRoomChatlogMessageComposer = 3434;
        public const int ModeratorRoomInfoMessageComposer = 1333;
        public const int ModeratorSupportTicketMessageComposer = 3609;
        public const int ModeratorSupportTicketResponseMessageComposer = 934;
        public const int ModeratorTicketChatlogMessageComposer = 607;
        public const int ModeratorUserChatlogMessageComposer = 3377;
        public const int ModeratorUserClassMessageComposer = 966;
        public const int ModeratorUserInfoMessageComposer = 2866;
        public const int ModeratorUserRoomVisitsMessageComposer = 1752;
        public const int MoodlightConfigMessageComposer = 2710;
        public const int MOTDNotificationMessageComposer = 2035;
        public const int MuteAllInRoomMessageComposer = 2533;
        public const int MutedMessageComposer = 826;
        public const int MysticBoxCloseComposer = 596;//MysticBox
        public const int MysticBoxPrizeComposer = 3712;//MysticBox
        public const int MysticBoxStartOpenComposer = 3201;//MysticBox
        public const int NameChangeUpdateMessageComposer = 563;
        public const int NavigatorCollapsedCategoriesMessageComposer = 1543;
        public const int NavigatorFlatCatsMessageComposer = 3244;
        public const int NavigatorLiftedRoomsMessageComposer = 3104;
        public const int NavigatorMetaDataParserMessageComposer = 3052;
        public const int NavigatorPreferencesMessageComposer = 518;
        public const int NavigatorSearchResultSetMessageComposer = 2690;
        public const int NavigatorSettingsMessageComposer = 2875;
        public const int NewBuddyRequestMessageComposer = 2219;
        public const int NewConsoleMessageMessageComposer = 1587;
        public const int NewGroupInfoMessageComposer = 2808;
        public const int NewUserExperienceGiftOfferMessageComposer = 91;
        public const int NuxAlertMessageComposer = 2023; // Nux Alerts
        public const int NuxItemListComposer = 3575; //@@@
        public const int NuxNotificationMessageComposer = 717;
        public const int NuxSuggestFreeGiftsMessageComposer = 3639;//@@@
        public const int NuxUserStatus = 3738; // Nux Alerts
        public const int ObjectAddMessageComposer = 1534;
        public const int ObjectRemoveMessageComposer = 2703;
        public const int ObjectsMessageComposer = 1778;
        public const int ObjectUpdateMessageComposer = 3776;
        public const int OpenBotActionMessageComposer = 1618;
        public const int OpenConnectionMessageComposer = 758;
        public const int OpenGiftMessageComposer = 56;
        public const int OpenHelpToolMessageComposer = 1121;
        public const int PerkAllowancesMessageComposer = 2586;
        public const int PetBreedingMessageComposer = 634;
        public const int PetHorseFigureInformationMessageComposer = 1924;
        public const int PetInformationMessageComposer = 2901;
        public const int PetInventoryMessageComposer = 3522;
        public const int PetTrainingPanelMessageComposer = 1164;
        public const int PlayableGamesMessageComposer = 3805;
        public const int PollContentsMessageComposer = 2997;// Polls
        public const int PollErrorAlertMessageComposer = 662;// Quickpolls
        public const int PollOfferMessageComposer = 3785;// Polls
        public const int PollQuestionsMessageComposer = 2997;// Quickpolls
        public const int PongMessageComposer = 3928;
        public const int PopularRoomTagsResultMessageComposer = 2012;
        public const int PostQuizAnswersMessageComposer = 2772;
        public const int PostUpdatedMessageComposer = 324;
        public const int PresentDeliverErrorMessageComposer = 3914;
        public const int ProfileInformationMessageComposer = 3898;
        public const int PromoArticlesMessageComposer = 286;
        public const int PromotableRoomsMessageComposer = 2468;
        public const int PurchaseErrorMessageComposer = 1404;
        public const int PurchaseOKMessageComposer = 869;
        public const int QuestAbortedMessageComposer = 3027;
        public const int QuestCompletedMessageComposer = 949;
        public const int QuestionAnswersMessageComposer = 2589;
        public const int QuestionParserMessageComposer = 2665;
        public const int QuestListMessageComposer = 3625;
        public const int QuestStartedMessageComposer = 230;
        public const int QuizDataMessageComposer = 2927;
        public const int QuizResultsMessageComposer = 2772;
        public const int RecyclerRewardsMessageComposer = 3164;
        public const int RefreshFavouriteGroupMessageComposer = 876;
        public const int RentableSpaceMessageComposer = 3559;
        public const int RentableSpacesErrorMessageComposer = 1868;
        public const int RespectNotificationMessageComposer = 2815;
        public const int RespectPetNotificationMessageComposer = 2788;
        public const int RoomCustomizedAlertComposer = 934; //###
        public const int RoomEntryInfoMessageComposer = 749;
        public const int RoomErrorNotifMessageComposer = 2913;
        public const int RoomEventMessageComposer = 1840;
        public const int RoomForwardMessageComposer = 160;
        public const int RoomInfoUpdatedMessageComposer = 3297;
        public const int RoomInviteMessageComposer = 3870;
        public const int RoomMuteSettingsMessageComposer = 2533;
        public const int RoomNotificationMessageComposer = 1992;
        public const int RoomPropertyMessageComposer = 2454;
        public const int RoomRatingMessageComposer = 482;
        public const int RoomReadyMessageComposer = 2031;
        public const int RoomRightsListMessageComposer = 1284;
        public const int RoomSettingsDataMessageComposer = 1498;
        public const int RoomSettingsSavedMessageComposer = 948;
        public const int RoomVisualizationSettingsMessageComposer = 3547;
        public const int SanctionStatusMessageComposer = 2221;
        public const int ScrSendUserInfoMessageComposer = 954;
        public const int SecretKeyMessageComposer = 3885;
        public const int SellablePetBreedsMessageComposer = 3331;
        public const int SendBullyReportMessageComposer = 3463;
        public const int SendGameInvitationMessageComposer = 904;
        public const int SendPollInvinteMessageComposer = 3785;// Quickpolls
        public const int SendRoomThumbnailAlertMessageComposer = 3595; //Camera
        public const int ServerErrorMessageComposer = 1004;
        public const int SetCameraPriceMessageComposer = 3878;
        public const int SetGroupIdMessageComposer = 1459;
        public const int SetJukeboxNowPlayingMessageComposer = 469; // Jukebox
        public const int SetJukeboxPlayListMessageComposer = 34; // Jukebox
        public const int SetJukeboxSongMusicDataMessageComposer = 3365; // Jukebox
        public const int SetUniqueIdMessageComposer = 1488;
        public const int ShoutMessageComposer = 1036;
        public const int SleepMessageComposer = 1797;
        public const int SlideObjectBundleMessageComposer = 3207;
        public const int SoundSettingsMessageComposer = 513;
        public const int StickyNoteMessageComposer = 2202;
        public const int SubmitBullyReportMessageComposer = 2674;
        public const int TalentLevelUpMessageComposer = 638;
        public const int TalentTrackLevelMessageComposer = 1203;
        public const int TalentTrackMessageComposer = 3406;
        public const int TargetOfferMessageComposer = 119;
        public const int ThreadCreatedMessageComposer = 1862;
        public const int ThreadDataMessageComposer = 509;
        public const int ThreadReplyMessageComposer = 2049;
        public const int ThreadsListDataMessageComposer = 1073;
        public const int ThreadUpdatedMessageComposer = 2528;
        public const int TradingAcceptMessageComposer = 2568;
        public const int TradingClosedMessageComposer = 1373;
        public const int TradingCompleteMessageComposer = 2720;
        public const int TradingConfirmedMessageComposer = 2568;
        public const int TradingErrorMessageComposer = 217;
        public const int TradingFinishMessageComposer = 1001;
        public const int TradingStartMessageComposer = 2505;
        public const int TradingUpdateMessageComposer = 2024;
        public const int TraxSongInfoMessageComposer = 3365; // Jukebox
        public const int UnbanUserFromRoomMessageComposer = 3429;
        public const int UniqueMachineIDMessageComposer = 1488;
        public const int UnknownCalendarMessageComposer = 2551;
        public const int UnknownGroupMessageComposer = 2445;
        public const int UpdateFavouriteGroupMessageComposer = 3403;
        public const int UpdateFavouriteRoomMessageComposer = 2524;
        public const int UpdateFreezeLivesMessageComposer = 2376;
        public const int UpdateHallOfFameCodeDataMessageComposer = 1745;// Hall
        public const int UpdateHallOfFameListMessageComposer = 3005;// Hall
        public const int UpdateMagicTileMessageComposer = 233;
        public const int UpdateStackHeightComposer = 558;
        public const int UpdateUsernameMessageComposer = 118;
        public const int UserChangeMessageComposer = 3920;
        public const int UserFlatCatsMessageComposer = 1562;
        public const int UserGameAchievementsMessageComposer = 2265;
        public const int UserNameChangeMessageComposer = 2182;
        public const int UserObjectMessageComposer = 2725;
        public const int UserPerksMessageComposer = 2586;
        public const int UserRemoveMessageComposer = 2661;
        public const int UserRightsMessageComposer = 411;
        public const int UsersMessageComposer = 374;
        public const int UserTagsMessageComposer = 1255;
        public const int UserTypingMessageComposer = 1717;
        public const int UserUpdateMessageComposer = 1640;
        public const int VideoOffersRewardsMessageComposer = 2125;
        public const int VoucherRedeemErrorMessageComposer = 714;
        public const int VoucherRedeemOkMessageComposer = 3336;
        public const int WardrobeMessageComposer = 3315;
        public const int WhisperMessageComposer = 2704;
        public const int WiredConditionConfigMessageComposer = 1108;
        public const int WiredEffectConfigMessageComposer = 1434;
        public const int WiredTriggerConfigMessageComposer = 383;
        public const int YouAreControllerMessageComposer = 780;
        public const int YouAreNotControllerMessageComposer = 2392;
        public const int YouAreOwnerMessageComposer = 339;
        public const int YoutubeDisplayPlaylistsMessageComposer = 1112;
        public const int YouTubeDisplayVideoMessageComposer = 1411;
	}
}